name: wildfire-detection 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - rasterio
  - earthengine-api
  - geemap
  - pytorch
  - scipy
  - matplotlib
  - pip
  - pip:
      - satlaspretrain-models
